In [1]:
from sklearn import datasets
import numpy as np

In [2]:
boston = datasets.load_boston()
print(boston.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [3]:
hoursing = datasets.fetch_california_housing()
print(hoursing.DESCR)

California housing dataset.

The original database is available from StatLib

    http://lib.stat.cmu.edu/

The data contains 20,640 observations on 9 variables.

This dataset contains the average house value as target variable
and the following input variables (features): average income,
housing average age, average rooms, average bedrooms, population,
average occupation, latitude, and longitude in that order.

References
----------

Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
Statistics and Probability Letters, 33 (1997) 291-297.




In [4]:
X,y = boston.data, boston.target

In [5]:
import sklearn.datasets as d
import numpy as np

In [8]:
reg_data = d.make_regression()
reg_data

(array([[-0.49526776,  1.00409481,  0.19811475, ...,  1.62868034,
         -1.10266592,  0.23575137],
        [-0.87995053,  1.0737584 ,  0.35475817, ...,  0.84636034,
          1.08323984,  0.67990654],
        [ 1.84523815,  1.21377023,  0.30860159, ...,  1.64061132,
          1.10454996, -0.0426878 ],
        ..., 
        [-0.18623492,  0.20077356,  1.2372846 , ...,  0.83760958,
         -1.40649865, -1.93928225],
        [ 0.84303361, -1.30072477,  0.7697774 , ..., -0.55646534,
          0.98553304,  2.07892992],
        [-1.18308549,  0.73194241,  1.73211894, ...,  0.48952998,
          0.59429781,  0.29334784]]),
 array([ 204.01370939,  -12.22950544, -128.56158335,  123.87896487,
         150.7138077 ,  -18.66731052,   43.08760213, -237.11295975,
         147.77155188,  414.21416499, -138.45321749, -323.52566348,
        -110.60910111, -373.39158543, -182.84290434,   35.85881325,
         -62.00266109,  487.80279052,  273.13361579,  492.33468206,
        -216.26219964, -219.8078

In [9]:
classification_set = d.make_classification(weights=[0.1])
np.bincount(classification_set[1])

array([12, 88])

In [11]:
blobs = d.make_blobs()
blobs

(array([[-7.45824173,  1.13734848],
        [-3.78324067, -4.51498812],
        [-6.7561399 ,  1.5409779 ],
        [-3.84783439, -3.59608427],
        [-4.79339587,  3.93410442],
        [-8.10049439,  2.4359226 ],
        [-3.82425405, -2.8007784 ],
        [-6.6705211 ,  2.16428124],
        [-5.94496209, -0.19554725],
        [-6.61049829,  3.33842115],
        [-6.33426506,  0.66961292],
        [-5.46523442, -0.40599809],
        [-3.50110488, -3.84617906],
        [-7.27044417,  2.45838577],
        [-5.00705484,  1.47122933],
        [-7.17030103,  2.05500396],
        [-5.66847305,  0.02002966],
        [-4.2291018 , -3.30386303],
        [-5.59129498, -0.50455437],
        [-5.1406908 ,  0.80806005],
        [-7.83006135, -0.36287445],
        [-4.92192116, -2.53312116],
        [-5.33267916,  0.31159568],
        [-3.7165519 , -4.50762407],
        [-6.60478603,  1.79829005],
        [-5.41441968, -4.44056105],
        [-6.25399614,  1.16662778],
        [-6.37473217,  2.111