In [1]:
from sklearn import datasets
import numpy as np

In [2]:
boston = datasets.load_boston()
print(boston.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [3]:
hoursing = datasets.fetch_california_housing()
print(hoursing.DESCR)

California housing dataset.

The original database is available from StatLib

    http://lib.stat.cmu.edu/

The data contains 20,640 observations on 9 variables.

This dataset contains the average house value as target variable
and the following input variables (features): average income,
housing average age, average rooms, average bedrooms, population,
average occupation, latitude, and longitude in that order.

References
----------

Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
Statistics and Probability Letters, 33 (1997) 291-297.




In [4]:
X,y = boston.data, boston.target

In [5]:
import sklearn.datasets as d
import numpy as np

In [6]:
reg_data = d.make_regression()
reg_data

(array([[-0.90390471,  2.52497627,  0.70971832, ...,  2.41835085,
         -0.81847806,  0.35227245],
        [-1.8218028 ,  0.52734473,  0.69680973, ..., -1.00634316,
          1.20760746, -1.01455349],
        [ 0.09639737, -0.29375919, -1.19297988, ...,  0.04091086,
          0.9130323 ,  0.09474403],
        ..., 
        [ 0.60270348,  0.07588815,  1.59155297, ..., -0.32679333,
         -0.08046831,  1.7012388 ],
        [ 2.11511259,  1.14319073,  1.53558612, ...,  2.5815518 ,
          2.66009638,  1.36141204],
        [ 0.48514408, -1.2977222 , -1.08492992, ..., -0.59898997,
         -0.82955649, -1.87348424]]),
 array([ -79.42364535, -231.68056558,   58.55466039,  -81.33432945,
         245.47710066,  -10.52565736,   13.05521527, -384.03729763,
         -78.05280788,  110.62705461,   84.6867485 ,  142.78949616,
          16.03256261, -127.74043366,   32.1505999 , -458.29517157,
         100.34458609,  -57.82184347,  -38.19949261,  157.04271403,
         266.10037891,  -77.6814

In [7]:
classification_set = d.make_classification(weights=[0.1])
np.bincount(classification_set[1])

array([10, 90])

In [8]:
blobs = d.make_blobs()
blobs

(array([[  4.88854980e+00,  -2.18042989e+00],
        [  6.74597864e+00,  -6.17975086e-01],
        [  5.87929979e+00,  -3.25459122e+00],
        [  1.23944665e+00,   5.57801982e+00],
        [ -5.05431396e+00,  -8.02530498e+00],
        [ -9.60664888e-01,   7.16788302e+00],
        [ -9.54546045e-01,   6.84518257e+00],
        [  6.17134165e-01,   4.97480244e+00],
        [ -2.05353791e+00,   5.92040677e+00],
        [ -1.86177014e+00,  -7.99431865e+00],
        [ -1.34055217e+00,   4.29564795e+00],
        [ -8.56825475e-01,   4.85162917e+00],
        [  6.23645239e+00,  -9.39528128e-01],
        [ -9.72798160e-01,   5.73636493e+00],
        [  5.25057181e+00,  -6.38933540e-01],
        [  5.89810149e+00,  -9.11436013e-03],
        [ -3.25732483e+00,  -7.31685278e+00],
        [  3.67932642e+00,  -1.58957503e+00],
        [ -4.34034423e+00,  -7.88456300e+00],
        [  4.44343993e+00,  -6.90886381e-01],
        [  6.97577745e+00,  -1.75497848e+00],
        [  5.51451843e+00,  -2.054

In [13]:
from sklearn import preprocessing
import numpy as np
print(X[:, :3].mean(axis=0))
print(X[:, :3].std(axis=0))

[  3.59376071  11.36363636  11.13677866]
[  8.58828355  23.29939569   6.85357058]


In [15]:
X_2 = preprocessing.scale(X[:, :3])
print(X_2.mean(axis=0))
print(X_2.std(axis=0))

[  6.34099712e-17  -6.34319123e-16  -2.68291099e-15]
[ 1.  1.  1.]


In [17]:
my_scaler = preprocessing.StandardScaler()
my_scaler.fit(X[:, :3])
my_scaler.transform(X[:, :3]).mean(axis=0)

array([  6.34099712e-17,  -6.34319123e-16,  -2.68291099e-15])

In [19]:
my_minmax_scaler = preprocessing.MinMaxScaler()
my_minmax_scaler.fit(X[:, :3])
my_minmax_scaler.transform(X[:, :3]).max(axis=0)


array([ 1.,  1.,  1.])